apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: ui
  labels:
    app: frontend
    group: csye7374
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend
      initContainers:
        - name: check-elastic-service
          image: busybox:1.28
          command: ['sh', '-c',
                    'until nslookup backend.api.svc.cluster.local; do echo waiting for backend; sleep 2; done;']
      containers:
      - name: f19-frontend
        image: placeholder
        imagePullPolicy: Always
        ports:
          - { containerPort: 8080,  protocol: TCP }
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
      imagePullSecrets:
        - name: mysecret