- name: Get RDS Security Group
  ec2_group_facts:
    region: "{{ region }}"
    filters:
      group-name: rds_security_group
  register: rds_security_group

- name: Delete RDS
  rds:
    command: delete
    region: "{{ region }}"
    wait: yes
    wait_timeout: 600
    instance_name: mysql-database

- name: Delete RDS Security Group
  ec2_group:
    region: "{{ region }}"
    group_id: "{{ rds_security_group.security_groups[0].group_id }}"
    state: absent
