apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: api
  labels:
    app: backend
    group: csye7220
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
      - name: f19-backend
        image: shubhankard34/recipe-backend:latest
        imagePullPolicy: Always
        ports:
          - { containerPort: 8080,  protocol: TCP }
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: credentials
                key: user

          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: credentials
                key: password

          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: credentials
                key: host
        resources:
          requests:
            memory: "1024Mi"
            cpu: "100m"
          limits:
            memory: "2048Mi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 1
          successThreshold: 1
