---
- name: Run on Local
  hosts: localhost
  connection: local
  become: false
  gather_facts: False
  vars_files:
    - vars/main.yaml
  roles:
    - role: setup-k8s-cluster
      when: command == "start"
      
    - role: helm
      when: command == "start"
    
    - role: prometheus
      when: command == "start"
    
    - role: grafana
      when: command == "start"
    
    - role: provision
      when: command == "start"
        
    - role: delete-k8s-cluster
      when: command == "delete"