version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image from Dockerfile
          command: | 
            docker build -t $DOCKER_USER/f19-t4-webapp-frontend:$CIRCLE_SHA1 -t $DOCKER_USER/f19-t4-webapp-frontend:latest .
      - run:
          name: Log into dockerhub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Push docker image to repository
          command: |
            docker push $DOCKER_USER/f19-t4-webapp-frontend:$CIRCLE_SHA1
      - run:
          name: Mark this image as latest
          command: |
            docker push $DOCKER_USER/f19-t4-webapp-frontend:latest
